import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}
group = 'mchorse.mappet'
version = mod_version

base {
    archivesName = 'mappet'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

minecraft {
    mappings channel: mappings_channel, version: mappings_version
    accessTransformer = file('src/main/resources/META-INF/mappet_at.cfg')

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                mappet {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                mappet {
                    source sourceSets.main
                }
            }
        }

        gameTest {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                mappet {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'mappet', '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
            mods {
                mappet {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation("org.reflections:reflections:0.10.2")
    implementation("net.minecraftforge:mergetool:0.2.3.3")
}

def processedJavaDir = "${buildDir}/generated/sources/mappet"

tasks.register('processSource', Sync) {
    outputs.upToDateWhen { false }

    from 'src/main/java'
    into processedJavaDir
    filter(ReplaceTokens, tokens: [
            MAPPET     : mod_version,
            MCLIB      : mclib_version,
            METAMORPH  : metamorph_version,
            BLOCKBUSTER: blockbuster_version,
            APERTURE   : aperture_version
    ])
}

tasks.named('compileJava', JavaCompile).configure {
    dependsOn tasks.named('processSource')
    source = fileTree(processedJavaDir)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('processResources', ProcessResources).configure {
    from('src/main/resources')
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).configure {
    archiveClassifier.set('')
    dependencies {
        include(dependency("org.reflections:reflections:0.10.2"))
        include(dependency("org.slf4j:slf4j-api:1.7.32"))
        include(dependency("org.javassist:javassist:3.28.0-GA"))
    }

    def dependenciesToRelocate = [
            'org.reflections',
            'org.slf4j',
            'javassist'
    ]

    dependenciesToRelocate.each { dependency ->
        relocate dependency, "mchorse.mappet.libs.${dependency}"
    }
}

tasks.named('jar', Jar).configure {
    finalizedBy(tasks.named('shadowJar'))
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.allJava
}

artifacts {
    archives tasks.named('sourcesJar')
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact tasks.named('jar')
            artifact tasks.named('sourcesJar')
        }
    }
}